# SPDX-FileCopyrightText: 2025 Yansheng Wang <ywang889@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

site_name: "Common SIPI Tools"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - pwl_linops: pwl_linops.md
